version: '2'

services:

  youtrack-server:
    image: esycat/youtrack
    container_name: youtrack
    ports:
      - 8082:8112
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/youtrack:/var/lib/youtrack
      - /data/youtrack/conf:/opt/youtrack/conf

  nginx:
    image: nginx
    links:
      - teamcity-server
    volumes:
      - "./server/yt.conf:/etc/nginx/conf.d/default.conf"
    environment:
      # set your domain name and email!
      VIRTUAL_HOST: youtrack.example.com
      LETSENCRYPT_HOST: youtrack.example.com
      LETSENCRYPT_EMAIL: username@example.ru

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./server/proxy.conf:/etc/nginx/conf.d/proxy.conf"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"