version: '2'

services:
    youtrack:
        image: jetbrains/youtrack:2018.1.41051
        container_name: youtrack
        restart: always
        volumes:
            - /opt/youtrack/data:/opt/youtrack/data
            - /opt/youtrack/conf:/opt/youtrack/conf
            - /opt/youtrack/logs:/opt/youtrack/logs
            - /opt/youtrack/backups:/opt/youtrack/backups

    nginx:
        image: nginx
        container_name: nginx
        restart: always
        links:
            - youtrack
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx/html:/usr/share/nginx/html"
            - "./nginx/certs:/etc/nginx/certs"
            - "./nginx/vhost.d:/etc/nginx/vhost.d"
            - "./nginx/conf.d:/etc/nginx/conf.d"
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
        env_file:
          - .env

    dockergen:
        image: jwilder/docker-gen
        container_name: docker-gen
        command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes_from:
          - nginx
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion:stable
        restart: always
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        volumes_from:
            - "nginx"
        environment:
            - NGINX_DOCKER_GEN_CONTAINER=docker-gen
            - NGINX_PROXY_CONTAINER=nginx
