version: '2'

volumes:
    youtrack_data: {}
    youtrack_home: {}
    youtrack_conf: {}

services:
    youtrack:
        build: ./youtrack
        container_name: youtrack
        restart: always
        volumes:
            - youtrack_data:/opt/youtrack/data
            - youtrack_conf:/opt/youtrack/conf
            - youtrack_home:/opt/youtrack/.youtrack

    nginx:
        image: nginx
        links:
            - youtrack
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx/html:/usr/share/nginx/html"
            - "./nginx/certs:/etc/nginx/certs"
            - "./nginx/vhost.d:/etc/nginx/vhost.d"
            - "./nginx/conf.d:/etc/nginx/conf.d"
        env_file:
          - .env

    dockergen:
        image: jwilder/docker-gen
        command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes_from:
          - nginx
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion:stable
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        volumes_from:
            - "nginx"
