version: '3'

services:
  youtrack:
    image: jetbrains/youtrack:2019.1.52973
    networks:
      - web
      - default
    container_name: youtrack
    ports:
      - "8080"
    volumes:
      - /opt/youtrack/data:/opt/youtrack/data
      - /opt/youtrack/conf:/opt/youtrack/conf
      - /opt/youtrack/logs:/opt/youtrack/logs
      - /opt/youtrack/backups:/opt/youtrack/backups
    labels:
      - "traefik.enable=true"
      - "traefik.backend=server"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.docker.network=web"
      - "traefik.port=8080"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  traefik:
    image: traefik
    restart: on-failure
    command:
      - --logLevel=ERROR
      - --docker
      - --docker.watch=true
      - --docker.exposedByDefault=false
      - --docker.domain=${VIRTUAL_HOST}
      - --defaultEntryPoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --acme=true
      - --acme.domains=${LETSENCRYPT_HOST}
      - --acme.email=${LETSENCRYPT_EMAIL}
      - --acme.storage=acme.json
      - --acme.OnHostRule=false
      - --acme.onDemand=false
      - --acme.entryPoint=https
      - --acme.httpChallenge
      - --acme.httpChallenge.entryPoint=http
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/acme.json:/acme.json
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  web:
    external: true